-- Create a table for public profiles using Supabase structure
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  vulnerability_score int,
  vulnerability_type text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Table for Phishing Reports (Heat Map)
create table reports (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users,
  type text check (type in ('SMS', 'Email', 'URL', 'QR')),
  description text,
  lat double precision,
  lng double precision,
  verified boolean default false
);

alter table reports enable row level security;

create policy "Everyone can read reports"
  on reports for select
  using ( true );

create policy "Authenticated users can create reports"
  on reports for insert
  with check ( auth.role() = 'authenticated' );

-- Table for Scan History
create table scans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users,
  url text,
  risk_score int,
  risk_level text,
  threat_type text
);

alter table scans enable row level security;

create policy "Users can see their own scans"
  on scans for select
  using ( auth.uid() = user_id );

create policy "Users can create scans"
  on scans for insert
  with check ( auth.uid() = user_id );

-- TRIGGERS FOR AUTOMATIC PROFILE CREATION
-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, vulnerability_score, vulnerability_type)
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    0,
    'Unassessed'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- ==========================================
-- FORUM SYSTEM
-- ==========================================

create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  title text not null,
  content text not null,
  category text default 'General',
  likes int default 0,
  is_verified boolean default false
);

alter table posts enable row level security;

create policy "Anyone can read posts" on posts for select using ( true );
create policy "Authenticated users can create posts" on posts for insert with check ( auth.role() = 'authenticated' );
create policy "Users can delete own posts" on posts for delete using ( auth.uid() = user_id );

create table comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_id bigint references posts(id) on delete cascade,
  user_id uuid references public.profiles(id),
  content text not null
);

alter table comments enable row level security;

create policy "Anyone can read comments" on comments for select using ( true );
create policy "Authenticated users can create comments" on comments for insert with check ( auth.role() = 'authenticated' );

-- ==========================================
-- REAL-TIME CHAT SYSTEM
-- ==========================================

create table chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  room_id text default 'general',
  content text not null,
  is_expert boolean default false
);

alter table chat_messages enable row level security;

create policy "Anyone can read chat" on chat_messages for select using ( true );
create policy "Authenticated users can chat" on chat_messages for insert with check ( auth.role() = 'authenticated' );

-- ==========================================
-- LMS (LEARNING SYSTEM)
-- ==========================================

create table user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id),
  module_id text not null,
  status text default 'in_progress', -- 'completed', 'locked'
  score int default 0,
  completed_at timestamp with time zone,
  unique(user_id, module_id)
);

alter table user_progress enable row level security;

create policy "Users can view own progress" on user_progress for select using ( auth.uid() = user_id );
create policy "Users can update own progress" on user_progress for insert with check ( auth.uid() = user_id );
create policy "Users can update own progress update" on user_progress for update using ( auth.uid() = user_id );
